name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io # 声明镜像源
        username: ${{ github.actor }} # 当前github 用户名
        password: ${{ secrets.HUB_GITHUB_TOKEN }}  #自行创建https://github.com/settings/tokens/new，然后需要在对应项目的Settings下创建secrets，不要用Environments的secrets
    - name: Build the Docker image
      run: |
        TAG=$(date +%s)
        chmod +x docker/main/build_nginx.sh docker/main/install_s6_overlay.sh docker/main/install_deps.sh  docker/main/fake_frigate_run
        docker build . --file docker/main/Dockerfile --tag ghcr.io/teo90/oort-nvr:$TAG
        docker push ghcr.io/teo90/oort-nvr:$TAG
